accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from . import views
from taskade import views as task_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('taskade/', include("taskade.urls")),
    path("accounts/", include("accounts.urls")),
    path("", task_views.index, name="home")
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskade/urls.py
from django.urls import path

from . import views

app_name = "tasks"

urlpatterns = [
    path("index/", views.index, name="index"),
    path("<int:id>/", views.detail, name="detail"),
    path("create/", views.create, name="create"),
    path("complete/<int:id>", views.complete, name="complete"),
]

accounts/models.py
from django.db import models

# Create your models here.

taskade/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):
    name = models.CharField(max_length=200)
    created_date = models.DateField(auto_now_add=True)
    due_date = models.DateField()
    priority = models.IntegerField()
    thumb = models.ImageField(default="default.png", blank=True)
    creator = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    
    def overdue(self):
        return self.due_date < datetime.date.today()

taskade/forms.py
from django import forms
from . import models

class CreateTask(forms.ModelForm):
    class Meta:
        model = models.Task
        fields = ['name', 'due_date', 'priority', 'thumb']
        

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # log the user in
            return redirect("tasks:index")
    else:
        form = UserCreationForm()
    return render(request, "accounts/signup.html", {"form": form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect("tasks:index")
    else:
        form = AuthenticationForm()
    return render(request, "accounts/login.html", {"form": form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("tasks:index")

mysite/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, "homepage.html")

taskade/views.py
from django.shortcuts import render, redirect
from .models import Task
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.

def index(request):
    tasks = Task.objects.filter(completed=False).order_by("due_date")
    return render(request, "taskade/index.html", {'tasks': tasks})

def detail(request, id):
    task = Task.objects.get(id=id)
    return render(request, "taskade/detail.html", {'task': task})

@login_required(login_url="/accounts/login/")
def create(request):
    if request.method == 'POST':
        form = forms.CreateTask(request.POST, request.FILES)
        if form.is_valid():
            # save to DB
            instance = form.save(commit=False)
            instance.creator = request.user
            instance.save()
            return redirect("tasks:index")
    else:
        form = forms.CreateTask()
    return render(request, "taskade/create.html", {"form": form})

def complete(request, id):
    if request.method == 'POST':
        task = Task.objects.get(id=id)
        task.completed = True
        task.save()
        return redirect('tasks:index')

accounts/templates/accounts/login.html
{% extends "base_layout.html" %}
{% block content %}

<h1>Login</h1>
<form class="site-form" action="{% url "accounts:login" %}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="Login">
</form>


{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base_layout.html" %}
{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url "accounts:signup" %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit", value="Signup">
    </form>

{% endblock content %}

taskade/templates/taskade/create.html
{% extends "base_layout.html" %}
{% block content %}
<div class="create-task">
    <h2>Create an Awesome new Task</h2>
    <form class="site-form" action=" {% url "tasks:create" %} " method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Create">
    </form>
</div>

{% endblock content %}

taskade/templates/taskade/detail.html
{% extends "base_layout.html" %}

{% block content %}
<div class="task-detail">
    <div class="task">
        <img src="{{task.thumb.url}}" alt="">
        <h2>{{task.name}} </h2>
        <p>Priority: {{task.priority}}</p>
        <p>Due Date: {{task.due_date}}</p>
        <form action={% url "tasks:complete" id=task.id %} method="post">
            {% csrf_token %}
            <button type="submit">Complete</button>
        </form>

    </div>
</div>


{% endblock content %}

taskade/templates/taskade/index.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="task-index-wrapper">
    <h1>Tasks</h1>
    <div class="tasks">
        {% for task in tasks %}
            <div class="task">
                <h2><a href="{% url "tasks:detail" id=task.id %}"> {{task.name}} </a></h2>
                <p> Priority: {{task.priority}} </p>
                <p> Due Date: {{task.due_date}} </p>
                <p> Created: {{task.created_date}} </p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>
<body>
    <h1>About us</h1>
    <p>We like Django</p>
</body>
</html>

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Taskade</title>
</head>
<body>
    <div class="wrapper">
        <nav>
            <ul class="nav-list">
                {% if user.is_authenticated %}
                <li>Hello, {{ user.username }}</li>
                <li><a href="{% url 'tasks:create' %}" class="highlight">New Task</a></li>
                <li class="logout-link">
                    <form class="logout-link" action={% url "accounts:logout" %} method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                
                {% endif %}
            </ul>

        </nav>
        <div class="content">
            {% block content %}
            {% endblock content %}
        </div>
        
    </div>
</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
</head>
<body>
    <h1>This is the homepage!</h1>
    <p>Welcome to taskade</p>
</body>
</html>